import * as THREE from 'three';
import './style.css';

const $=id=>document.getElementById(id); const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
let scene,camera,renderer,composer,clock,player,playerVel=new THREE.Vector3(),yaw=0,keys={},state='title',timeLeft=150,score=0,health=100,cores=[],drones=[],particles=[],beacon,extractRing,ambient,boostCooldown=0,beamCooldown=0,shake=0;
const colliders=[]; const worldY=0;
const mat=(color,emissive=0,rough=.5,metal=.4)=>new THREE.MeshStandardMaterial({color,emissive,emissiveIntensity:emissive?2.2:0,roughness:rough,metalness:metal});
const cyan=0x44dfff, amber=0xffb52e, steel=0x172531, dark=0x081018, red=0xff405a;

function makeBox(x,y,z,sx,sy,sz,material=mat(steel)){const o=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),material);o.position.set(x,y,z);scene.add(o);return o}
function addLight(x,y,z,color,intensity,distance){const l=new THREE.PointLight(color,intensity,distance);l.position.set(x,y,z);scene.add(l);return l}
function cyl(x,y,z,r,h,material,seg=12){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,seg),material);o.position.set(x,y,z);scene.add(o);return o}
function label(text,x,y,z,color=0x75e4fa){const c=document.createElement('canvas'),ctx=c.getContext('2d');c.width=512;c.height=64;ctx.font='700 24px Space Mono';ctx.fillStyle='#'+color.toString(16).padStart(6,'0');ctx.fillText(text,6,34);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthTest:false}));s.position.set(x,y,z);s.scale.set(5,.62,1);scene.add(s);return s}
function buildWorld(){
  scene=new THREE.Scene();scene.background=new THREE.Color(0x040811);scene.fog=new THREE.FogExp2(0x07111a,.012);
  camera=new THREE.PerspectiveCamera(67,innerWidth/innerHeight,.1,500);camera.position.set(0,7,14);
  renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;$('game').appendChild(renderer.domElement);
  scene.add(new THREE.HemisphereLight(0x326070,0x020308,.35));addLight(0,18,0,0x2edbff,15,70);addLight(-30,6,-30,0xff863d,10,42);
  // suspended platforms and multiple routes
  makeBox(0,-1,0,34,1.3,30,mat(0x121f29,.02,.68,.82));makeBox(-31,-5,-23,22,1,18,mat(0x101d26,.01,.7,.8));makeBox(28,-9,-35,18,1,21,mat(0x101d26,.01,.7,.8));makeBox(35,-13,7,16,1,18,mat(0x101d26,.01,.7,.8));
  const rails=mat(0x172e38,0x092b36,.34,.9); for(let x=-15;x<=15;x+=3){makeBox(x,-.18,-14,.11,.15,28,rails)}
  // elevated catwalks
  makeBox(-13,4,-15,4,.55,22,mat(0x1e3038,.01,.5,.8));makeBox(13,7,-28,4,.55,18,mat(0x1e3038,.01,.5,.8));makeBox(26,10,-20,17,.55,3,mat(0x1e3038,.01,.5,.8));
  for(const x of [-15,-11,11,15,25,30]){for(const z of [-14,-5,4]){cyl(x,-.7,z,.14,1.4,mat(cyan,cyan));}}
  // void geometry: drifting slabs and distant pylons
  for(let i=0;i<36;i++){const x=(Math.random()-.5)*150,z=-20-Math.random()*100,y=-18+Math.random()*26;const o=makeBox(x,y,z,Math.random()*3+.5,Math.random()*2+.2,Math.random()*3+.5,mat(0x0b1922));o.userData.spin=(Math.random()-.5)*.2}
  for(let i=0;i<18;i++){const x=(Math.random()-.5)*95,z=-45-Math.random()*55;makeBox(x,Math.random()*5-5,z,.2,Math.random()*13+3,.2,mat(cyan,cyan));}
  // hazard pylons
  for(const p of [[-8,0,-8],[8,0,-9],[-26,-4,-24],[27,-8,-35]]){cyl(p[0],p[1]+2,p[2],.45,4,mat(0x1b2d37));cyl(p[0],p[1]+4.15,p[2],.16,.25,mat(amber,amber));addLight(p[0],p[1]+4,p[2],amber,2,10)}
  beacon=new THREE.Group();beacon.position.set(0,0,12);scene.add(beacon);cyl(0,.3,12,2.8,.25,mat(amber,amber));cyl(0,1.4,12,.15,2.2,mat(amber,amber));extractRing=new THREE.Mesh(new THREE.TorusGeometry(3.5,.12,8,48),mat(amber,amber));extractRing.rotation.x=Math.PI/2;extractRing.position.set(0,.45,12);scene.add(extractRing);label('EXTRACTION // RETURN HERE',-4,1,12,amber);
  makePlayer();createCores();createDrones();createParticles();
}
function makePlayer(){player=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(.85,1.5,5,10),mat(0x1b566a,cyan,.23,.8));body.rotation.z=Math.PI/2;player.add(body);const canopy=new THREE.Mesh(new THREE.SphereGeometry(.52,16,8),mat(0x0b1620,cyan,.1,.8));canopy.scale.set(1.25,.65,.85);canopy.position.set(.15,.45,0);player.add(canopy);for(const x of [-.65,.65]){const t=new THREE.Mesh(new THREE.CylinderGeometry(.14,.22,.6,10),mat(amber,amber));t.rotation.z=Math.PI/2;t.position.set(x,-.45,0);player.add(t)}player.position.set(0,1,8);scene.add(player);}
function createCores(){const ps=[[-9,1,-6],[10,5,-15],[-28,-3,-24],[29,-7,-35],[27,11,-20]];ps.forEach((p,i)=>{const g=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(.8,.09,8,20),mat(amber,amber));ring.rotation.x=Math.PI/2;g.add(ring);const core=new THREE.Mesh(new THREE.OctahedronGeometry(.45),mat(0xe9fbff,cyan,.12,.6));g.add(core);g.position.set(...p);g.userData.baseY=p[1];g.userData.collected=false;scene.add(g);cores.push(g);addLight(p[0],p[1],p[2],cyan,2.5,8)});}
function droneAt(x,y,z,route){const g=new THREE.Group();const shell=new THREE.Mesh(new THREE.IcosahedronGeometry(1,1),mat(0x31232b,red,.35,.8));g.add(shell);const eye=new THREE.Mesh(new THREE.SphereGeometry(.22,10,6),mat(red,red));eye.position.z=1;g.add(eye);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.15,.06,6,18),mat(red,red));ring.rotation.x=Math.PI/2;g.add(ring);g.position.set(x,y,z);g.userData={route,idx:0,state:'PATROL',alert:0,attack:0,baseY:y};scene.add(g);drones.push(g);addLight(x,y,z,red,1.4,10)}
function createDrones(){droneAt(-4,3,-17,[[-4,3,-17],[-13,5,-17],[-13,5,-4],[-4,3,-4]]);droneAt(17,9,-28,[[17,9,-28],[29,10,-20],[24,9,-13],[13,7,-18]]);droneAt(-25,-1,-28,[[-25,-1,-28],[-35,-4,-20],[-27,-4,-14],[-20,-1,-23]])}
function createParticles(){const geo=new THREE.BufferGeometry(),arr=[];for(let i=0;i<500;i++)arr.push((Math.random()-.5)*110,Math.random()*45-12,-Math.random()*140-5);geo.setAttribute('position',new THREE.Float32BufferAttribute(arr,3));const p=new THREE.Points(geo,new THREE.PointsMaterial({color:0x4adfff,size:.09,transparent:true,opacity:.45}));scene.add(p);particles.push(p)}
function start(){state='play';timeLeft=150;score=0;health=100;player.position.set(0,1,8);playerVel.set(0,0,0);yaw=0;cores.forEach(c=>{c.userData.collected=false;c.visible=true});drones.forEach(d=>{d.userData.alert=0;d.userData.state='PATROL'});$('overlay').classList.add('hidden');$('resultPanel').classList.add('hidden');$('pausePanel').classList.add('hidden');$('hud').classList.remove('hidden');updateHud();if(!ambient){ambient=new AudioContext();const o=ambient.createOscillator(),gain=ambient.createGain();o.type='sine';o.frequency.value=55;gain.gain.value=.018;o.connect(gain).connect(ambient.destination);o.start()}}
function beep(freq=480,dur=.08){if(!ambient)return;const o=ambient.createOscillator(),g=ambient.createGain();o.type='square';o.frequency.value=freq;g.gain.setValueAtTime(.06,ambient.currentTime);g.gain.exponentialRampToValueAtTime(.001,ambient.currentTime+dur);o.connect(g).connect(ambient.destination);o.start();o.stop(ambient.currentTime+dur)}
function updateHud(){const mins=Math.floor(Math.max(0,timeLeft)/60);const secs=Math.ceil(Math.max(0,timeLeft)%60)%60;$('coreCount').textContent=`${cores.filter(c=>c.userData.collected).length} / 5`;$('timer').textContent=`${String(mins).padStart(2,'0')}:${String(secs).padStart(2,'0')}`;$('score').textContent=String(Math.max(0,Math.floor(score))).padStart(6,'0');$('healthBar').style.width=`${health}%`;$('healthBar').style.background=health<35?'#ff405a':'#75e4fa'}
function collectCheck(){for(const c of cores)if(!c.userData.collected&&player.position.distanceTo(c.position)<2){c.userData.collected=true;c.visible=false;score+=1000;beep(780,.15);$('status').textContent='CORE SECURED // SIGNAL SPIKING';setTimeout(()=>{if(state==='play')$('status').textContent='SIGNAL CLEAN // MOVE OUT'},1200)}if(cores.every(c=>c.userData.collected)&&player.position.distanceTo(beacon.position)<4){finish(true)}}
function hazardCheck(){for(const p of [[-8,2,-8],[8,2,-9],[-26,-2,-24],[27,-6,-35]])if(player.position.distanceTo(new THREE.Vector3(...p))<1.35){damage(12);playerVel.multiplyScalar(-.55);player.position.y+=.25;$('status').textContent='IMPACT // HULL INTEGRITY FALLING';break}}
function damage(n){health-=n;shake=.4;beep(110,.12);if(health<=0)finish(false);}
function finish(win){state='result';$('hud').classList.add('hidden');$('resultPanel').classList.remove('hidden');$('resultKicker').textContent=win?'RECOVERY REPORT':'HULL FAILURE // BLACKSITE 07';$('resultTitle').textContent=win?'RUN COMPLETE':'YOU WENT DARK';$('resultCopy').textContent=win?`Five cores recovered. Extraction window cleared with ${Math.ceil(timeLeft)} seconds left.`:'The facility kept the cores. It usually does. Recalibrate and try again.';$('finalScore').textContent=String(Math.max(0,Math.floor(score+(win?timeLeft*20:0)))).padStart(6,'0');beep(win?920:80,.35)}
function update(dt){if(state!=='play')return;timeLeft-=dt;boostCooldown-=dt;beamCooldown-=dt;if(timeLeft<=0){finish(false);return}
  const input=new THREE.Vector3((keys.KeyD?1:0)-(keys.KeyA?1:0),0,(keys.KeyS?1:0)-(keys.KeyW?1:0));if(input.lengthSq())input.normalize();const boosting=keys.Space&&boostCooldown<=0;if(boosting){boostCooldown=1.25;playerVel.add(new THREE.Vector3(0,keys.Space?6:0,0));score+=10;beep(320,.1)}
  input.applyAxisAngle(new THREE.Vector3(0,1,0),yaw);playerVel.x+=input.x*dt*18;playerVel.z+=input.z*dt*18;playerVel.y-=16*dt;playerVel.multiplyScalar(Math.pow(.88,dt*60));playerVel.x=clamp(playerVel.x,-16,16);playerVel.z=clamp(playerVel.z,-16,16);if(player.position.y<.5){player.position.y=.5;playerVel.y=Math.max(playerVel.y,0)}player.position.addScaledVector(playerVel,dt);player.position.x=clamp(player.position.x,-45,45);player.position.z=clamp(player.position.z,-55,15);if(player.position.y<-16)damage(100);
  player.rotation.z=-playerVel.x*.025;player.rotation.x=playerVel.z*.018;player.rotation.y=yaw; if(keys.ShiftLeft&&beamCooldown<=0){beamCooldown=1;let nearest=cores.filter(c=>!c.userData.collected).sort((a,b)=>player.position.distanceTo(a.position)-player.position.distanceTo(b.position))[0];if(nearest&&player.position.distanceTo(nearest)<15){player.position.lerp(nearest.position,.32);beep(620,.1);}}
  collectCheck();hazardCheck();drones.forEach(d=>updateDrone(d,dt));cores.forEach((c,i)=>{if(c.visible){c.rotation.y+=dt*1.8;c.position.y=c.userData.baseY+Math.sin(clock.elapsedTime*2+i)*.25}});extractRing.rotation.z+=dt*1.2;cameraFollow(dt);updateHud();
}
function updateDrone(d,dt){const dist=d.position.distanceTo(player.position);if(dist<14)d.userData.alert+=dt*1.8;else d.userData.alert=Math.max(0,d.userData.alert-dt*.5);if(d.userData.alert>2)d.userData.state='PURSUIT';else if(d.userData.alert>0.4)d.userData.state='DETECTION';else d.userData.state='PATROL';let target=d.userData.route[d.userData.idx];if(d.userData.state==='PURSUIT'){target=player.position;if(dist<4){d.userData.attack+=dt;if(d.userData.attack>.8){damage(9);d.userData.attack=0}}}else{if(d.position.distanceTo(new THREE.Vector3(...target))<1.2)d.userData.idx=(d.userData.idx+1)%d.userData.route.length}const v=new THREE.Vector3(...target).sub(d.position);if(v.length()>0.2)d.position.addScaledVector(v.normalize(),dt*(d.userData.state==='PURSUIT'?5:2.5));d.rotation.y+=dt*2;d.children[1].material.emissiveIntensity=d.userData.state==='PURSUIT'?5:2.2}
function cameraFollow(dt){const desired=new THREE.Vector3(player.position.x*.32,player.position.y+6.5,player.position.z+10);camera.position.lerp(desired,1-Math.pow(.001,dt));const look=player.position.clone().add(new THREE.Vector3(0,1,-5));camera.lookAt(look);if(shake>0){camera.position.x+=(Math.random()-.5)*shake;camera.position.y+=(Math.random()-.5)*shake;shake-=dt}}
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.05);update(dt);renderer.render(scene,camera)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Escape'&&state==='play'){state='pause';$('pausePanel').classList.remove('hidden')}else if(e.code==='Escape'&&state==='pause'){resume()}});addEventListener('keyup',e=>keys[e.code]=false);function resume(){state='play';$('pausePanel').classList.add('hidden')}
$('startBtn').onclick=start;$('resumeBtn').onclick=resume;$('restartBtn').onclick=start;$('replayBtn').onclick=start;
buildWorld();clock=new THREE.Clock();loop();

